# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: go-discord-music
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
      - '386'
      - s390x
      - ppc64le
      - riscv64
      - mips64
      - mips64le
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w
      - -X 'go-discord-music/pkg/version.Version={{.Version}}'
      - -X 'go-discord-music/pkg/version.Commit={{.Commit}}'
      - -X 'go-discord-music/pkg/version.Date={{.Date}}'
      - -extldflags "-static"

archives:
  - formats: ['tar.xz']
    files:
        - README.md
    format_overrides:
      - goos: windows
        formats: ['zip']
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Version }}-snapshot-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

signs:
  - artifacts: all
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

sboms:
  - artifacts: archive

release:
  draft: true
  footer: >-
    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

blobs:
  - provider: s3
    region: auto
    endpoint: https://8be772befd147a8df540aae0fa15c047.r2.cloudflarestorage.com
    bucket: public-files

#announce:
#  bluesky:
#    enabled: true
#    username: releases.cyberjake.xyz


dockers_v2:
  - dockerfile: Dockerfile
    images:
      - "cyb3rjak3/go-discord-music"
      - "ghcr.io/cyb3r-jak3/go-discord-music"
    tags:
      - "latest"
      - "{{.Tag}}"
      - "v{{ .Major }}"
    annotations:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    platforms:
      - linux/amd64
      - linux/arm64